// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace CommerceBankWebAppDemo.Data.Commerce
{
    [Keyless]
    [Table("location_constraint")]
    public partial class LocationConstraint
    {
        [Column("notificationID")]
        public int NotificationId { get; set; }
        [Required]
        [Column("location")]
        [StringLength(200)]
        public string Location { get; set; }

        [ForeignKey(nameof(NotificationId))]
        public virtual UserToNotifications Notification { get; set; }
    }
}