// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace CommerceBankWebAppDemo.Data.Commerce
{
    [Keyless]
    public partial class Login
    {
        [Required]
        [Column("username")]
        [StringLength(50)]
        public string Username { get; set; }
        [Required]
        [Column("password")]
        [MaxLength(64)]
        public byte[] Password { get; set; }
        [Column("userID")]
        public int UserId { get; set; }

        [ForeignKey(nameof(UserId))]
        public virtual UserInfo User { get; set; }
    }
}