// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace CommerceBankWebAppDemo.Data.Commerce
{
    [Keyless]
    [Table("userstoaccounts")]
    public partial class Userstoaccounts
    {
        [Column("userID")]
        public int? UserId { get; set; }
        [Column("accountID")]
        public int? AccountId { get; set; }

        [ForeignKey(nameof(AccountId))]
        public virtual Accounts Account { get; set; }
        [ForeignKey(nameof(UserId))]
        public virtual UserInfo User { get; set; }
    }
}