// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace EndToEndTest.Data.CommerceDataModels
{
    [Table("accounts")]
    public partial class Accounts
    {
        public Accounts()
        {
            Transactionsmaster = new HashSet<Transactionsmaster>();
        }

        [Key]
        [Column("accountID")]
        public int AccountId { get; set; }
        [Column("balance", TypeName = "decimal(20, 2)")]
        public decimal? Balance { get; set; }
        [Column("lasttransaction", TypeName = "date")]
        public DateTime? Lasttransaction { get; set; }

        [InverseProperty("Account")]
        public virtual ICollection<Transactionsmaster> Transactionsmaster { get; set; }
    }
}