// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace EndToEndTest.Data.CommerceDataModels
{
    [Table("transactionsmaster")]
    public partial class Transactionsmaster
    {
        [Required]
        [Column("userID")]
        [StringLength(450)]
        public string UserId { get; set; }
        [Column("accountID")]
        public int AccountId { get; set; }
        [Column("transactiondate", TypeName = "datetime")]
        public DateTime Transactiondate { get; set; }
        [Key]
        [Column("transactionID")]
        public long TransactionId { get; set; }
        [Column("openingbalance", TypeName = "decimal(20, 2)")]
        public decimal Openingbalance { get; set; }
        [Required]
        [Column("transactiontype")]
        [StringLength(2)]
        public string Transactiontype { get; set; }
        [Column("transactionamount", TypeName = "decimal(20, 2)")]
        public decimal Transactionamount { get; set; }
        [Required]
        [Column("description")]
        [StringLength(256)]
        public string Description { get; set; }
        [Required]
        [Column("locationState")]
        [StringLength(200)]
        public string LocationState { get; set; }
        [Column("islastID")]
        public int IslastId { get; set; }

        [ForeignKey(nameof(AccountId))]
        [InverseProperty(nameof(Accounts.Transactionsmaster))]
        public virtual Accounts Account { get; set; }
    }
}