// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace CommerceBankWebAppDemo.Data.Commerce
{
    public partial class UserInfo
    {
        public UserInfo()
        {
            Transactionsmaster = new HashSet<Transactionsmaster>();
        }

        [Key]
        [Column("userID")]
        public int UserId { get; set; }
        [Required]
        [Column("firstname")]
        [StringLength(100)]
        public string Firstname { get; set; }
        [Required]
        [Column("lastname")]
        [StringLength(100)]
        public string Lastname { get; set; }
        [Column("additionalname")]
        [StringLength(50)]
        public string Additionalname { get; set; }
        [Required]
        [Column("address1")]
        [StringLength(150)]
        public string Address1 { get; set; }
        [Column("address2")]
        [StringLength(100)]
        public string Address2 { get; set; }
        [Required]
        [Column("city")]
        [StringLength(100)]
        public string City { get; set; }
        [Required]
        [Column("state")]
        [StringLength(100)]
        public string State { get; set; }
        [Required]
        [Column("country")]
        [StringLength(120)]
        public string Country { get; set; }
        [Column("email")]
        [StringLength(100)]
        public string Email { get; set; }
        [Column("phonenumber")]
        [StringLength(20)]
        public string Phonenumber { get; set; }
        [Column("dateofbirth", TypeName = "date")]
        public DateTime Dateofbirth { get; set; }

        [InverseProperty("User")]
        public virtual ICollection<Transactionsmaster> Transactionsmaster { get; set; }
    }
}