// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace EndToEndTest.Data.CommerceDataModels
{
    [Table("amount_constraint")]
    public partial class AmountConstraint
    {
        [Key]
        [Column("notificationID")]
        public int NotificationId { get; set; }
        [Column("min", TypeName = "decimal(15, 2)")]
        public decimal Min { get; set; }
        [Column("max", TypeName = "decimal(15, 2)")]
        public decimal Max { get; set; }

        [ForeignKey(nameof(NotificationId))]
        [InverseProperty(nameof(UserToNotifications.AmountConstraint))]
        public virtual UserToNotifications Notification { get; set; }
    }
}