// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace EndToEndTest.Data.CommerceDataModels
{
    [Table("time_constraint")]
    public partial class TimeConstraint
    {
        [Key]
        [Column("notificationID")]
        public int NotificationId { get; set; }
        [Column("time_in")]
        public TimeSpan TimeIn { get; set; }
        [Column("time_out")]
        public TimeSpan TimeOut { get; set; }

        [ForeignKey(nameof(NotificationId))]
        [InverseProperty(nameof(UserToNotifications.TimeConstraint))]
        public virtual UserToNotifications Notification { get; set; }
    }
}