// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace EndToEndTest.Data.CommerceDataModels
{
    [Keyless]
    [Table("triggeredNotif")]
    public partial class TriggeredNotif
    {
        [Column("trigNotifId")]
        public int TrigNotifId { get; set; }
        [Column("dateAdded", TypeName = "datetime")]
        public DateTime DateAdded { get; set; }
        [Required]
        [Column("emailBody")]
        public string EmailBody { get; set; }
        [Required]
        [Column("emailSentTo")]
        [StringLength(256)]
        public string EmailSentTo { get; set; }
        [Column("isEmailSent")]
        public bool IsEmailSent { get; set; }
    }
}