// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace EndToEndTest.Data.CommerceDataModels
{
    [Table("userToNotifications")]
    public partial class UserToNotifications
    {
        [Required]
        [Column("userID")]
        [StringLength(450)]
        public string UserId { get; set; }
        [Key]
        [Column("notificationID")]
        public int NotificationId { get; set; }
        public int Jan { get; set; }
        public int Feb { get; set; }
        public int Mar { get; set; }
        public int Apr { get; set; }
        public int May { get; set; }
        public int Jun { get; set; }
        public int Jul { get; set; }
        public int Aug { get; set; }
        public int Sep { get; set; }
        public int Oct { get; set; }
        public int Nov { get; set; }
        public int Dec { get; set; }

        [InverseProperty("Notification")]
        public virtual AmountConstraint AmountConstraint { get; set; }
        [InverseProperty("Notification")]
        public virtual LocationConstraint LocationConstraint { get; set; }
        [InverseProperty("Notification")]
        public virtual TimeConstraint TimeConstraint { get; set; }
    }
}