// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace EndToEndTest.Data.CommerceDataModels
{
    [Keyless]
    [Table("userstoaccounts")]
    public partial class Userstoaccounts
    {
        [Required]
        [Column("userID")]
        [StringLength(450)]
        public string UserId { get; set; }
        [Column("accountID")]
        public int AccountId { get; set; }

        [ForeignKey(nameof(AccountId))]
        public virtual Accounts Account { get; set; }
    }
}